const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.css':'text/css','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(data)});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],dialogs=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',async d=>{dialogs.push(d.message());await d.accept()});await page.goto('http://127.0.0.1:'+server.address().port);
 await page.evaluate(()=>demoVerifiedDriver());await page.evaluate(()=>go('membership'));assert.equal(await page.locator('#membership').isVisible(),true);
 assert.equal(await page.evaluate(()=>hasPremium()),false);
 assert.equal(await page.locator('#supportType option').filter({hasText:'Araç gelmedi'}).count(),0);
 assert.equal(await page.locator('#supportType option').filter({hasText:'Yük hazır değil'}).count(),1);
 await page.locator('#support .support-btn[data-topic="Yük hazır değil"]').evaluate(b=>b.click());assert.equal(await page.locator('#supportType').inputValue(),'Yük hazır değil');
 await page.evaluate(()=>activatePremium());assert.equal(await page.evaluate(()=>hasPremium()),true);
 await page.reload();assert.equal(await page.evaluate(()=>hasPremium()),true);await page.evaluate(()=>endPremium());assert.equal(await page.evaluate(()=>hasPremium()),false);
 const loadId=await page.evaluate(()=>openLoads()[0].id);await page.evaluate(id=>showProfit(id),loadId);assert.equal(await page.locator('#profitDialog').isVisible(),true);
 const result=await page.evaluate(()=>profitResult({price:20000,platformFee:500},{distance:500,empty:100,consumption:30,fuel:50,tolls:1000,other:200}));assert.equal(result.cost,10700);assert.equal(result.net,9300);
 await page.locator('#cost-fuel').fill('-1');assert.ok((await page.locator('#profitResult').innerText()).includes('pozitif'));await page.evaluate(()=>document.getElementById('profitDialog').close());
 await page.evaluate(()=>openDriverIssue());await page.locator('#supportDetail').fill('A local support report <script>');await page.locator('#supportForm button').click();assert.equal(await page.locator('#supportTickets .item').count(),1);await page.reload();await page.evaluate(()=>go('support'));assert.equal(await page.locator('#supportTickets .item').count(),1);
 await page.evaluate(()=>{const t=trip();t.stage='Teslim edildi';save();go('ratings')});assert.equal(await page.locator('#rateCompanySelect option[value="T-DEMO2"]').count(),1);
 await page.evaluate(()=>submitCompanyRating());assert.equal(await page.evaluate(()=>db.tripReviews.length),1);await page.evaluate(()=>submitCompanyRating());assert.equal(await page.evaluate(()=>db.tripReviews.length),1);
 await page.evaluate(()=>demoVerifiedCompany());
 assert.equal(await page.locator('#supportType option').filter({hasText:'Araç gelmedi'}).count(),1);
 assert.equal(await page.locator('#supportType option').filter({hasText:'Yük hazır değil'}).count(),0);
 await page.evaluate(()=>go('ratings'));assert.equal(await page.locator('#rateDriverSelect option[value="T-DEMO2"]').count(),1);await page.evaluate(()=>submitDriverRating());assert.equal(await page.evaluate(()=>db.tripReviews.length),2);
 await page.evaluate(()=>demoVerifiedDriver());assert.deepEqual(await page.evaluate(()=>rewardProgress()),{count:1,score:5});await page.evaluate(()=>claimReward(10));assert.equal(await page.evaluate(()=>db.rewardClaims.length),0);
 await page.evaluate(()=>{const l={id:'QA-NORMAL',loadNo:'QA-NORMAL',from:'Gaziantep',to:'Adana',vehicleType:'Tır',weight:1000,pickupTime:new Date(Date.now()+3600000).toISOString(),deliveryTime:new Date(Date.now()+7200000).toISOString(),ownerId:'C-DEMO'};db.loads.push(l);assignBackhaul(l.id)});assert.equal(await page.evaluate(()=>db.trips.some(t=>t.loadId==='QA-NORMAL')),false);
 await page.evaluate(()=>{const now=new Date();db.birthdayPreferences[getSession().id]={month:now.getMonth()+1,day:now.getDate()};claimBirthday();claimBirthday()});assert.equal(await page.evaluate(()=>db.rewardClaims.filter(c=>String(c.threshold).startsWith('birthday')).length),1);assert.equal(await page.evaluate(()=>hasPremium()),true);
 await page.evaluate(()=>assignBackhaul('QA-NORMAL'));assert.equal(await page.evaluate(()=>db.trips.filter(t=>t.loadId==='QA-NORMAL').length),1);
 await page.evaluate(()=>{const v=myVehicle();const t=db.trips.find(t=>t.loadId==='QA-NORMAL');t.stage='Teslim edildi';selectedTrip='T-DEMO2';endPremium()});
 await page.evaluate(()=>{const t=trip();t.stage='Yolda';save();toggleWait();t.waits[0].start=Date.now()-180*60000;const l=load(t.loadId);l.freeWait=120;l.waitRate=600;toggleWait();go('driverJobs')});assert.ok((await page.locator('#waitTracking').innerText()).includes('600'));
 await page.evaluate(()=>{const l=openLoads()[0];l.pickupTime=new Date(Date.now()-10000).toISOString();window.expired=l.id});assert.equal(await page.evaluate(()=>openLoads().some(l=>l.id===window.expired)),false);
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>go('membership'));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.resolve(root,'../YukYol-review/membership-mobile.png'),fullPage:true});
 await page.evaluate(()=>showProfit(db.loads[0].id));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.resolve(root,'../YukYol-review/profit-mobile.png'),fullPage:true});assert.deepEqual(errors,[]);
 console.log('PASS: membership persistence, profit calculations, support persistence, trip-only reviews, duplicate protection, reward eligibility, waiting fees, expired loads, mobile layout, no page errors.');
 }finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
